version: '3'
services:
  auth-db:
    image: postgres:11
    container_name: auth-db
    restart: always
    networks:
      - sales-network
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432

  product-db:
    image: postgres:11
    container_name: product-db
    restart: always
    networks:
      - sales-network
    environment:
      - POSTGRES_DB=product-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5433:5432

  sales-db:
    image: mongo
    container_name: sales-db
    restart: always
    networks:
      - sales-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27017:27017

  sales-rabbit:
    image: rabbitmq:3-management
    container_name: sales-rabbit
    hostname: sales-rabbit
    restart: always
    networks:
      - sales-network
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672

  product-api:
    build: './product-api'
    container_name: product-api
    depends_on:
      - product-db
      - sales-rabbit
    networks:
      - sales-network
    environment:
      - JWT_SECRET=f4c77928acb18a37a7f8b5e7af63f4fd
      - DB_HOST=product-db
      - DB_PORT=5432
      - DB_NAME=product-db
      - DB_USER=admin
      - DB_PASS=123456
      - RABBIT_MQ_HOST=sales-rabbit
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER=guest
      - RABBIT_MQ_PASSWORD=guest
      - SALES_HOST=sales-api
      - SALES_PORT=8082
      - PORT=8081
    ports:
      - 8081:8081

  sales-api:
    build: './sales-api'
    container_name: sales-api
    depends_on:
      - sales-db
      - sales-rabbit
    networks:
      - sales-network
    environment:
      - JWT_SECRET=f4c77928acb18a37a7f8b5e7af63f4fd
      - MONGO_DB_URL=mongodb://admin:123456@sales-db:27017/sales?authSource=admin
      - RABBIT_MQ_URL=amqp://sales-rabbit:5672
      - PRODUCT_API_URL=http://product-api:8081/api/product
      - PORT=8082
      - NODE_ENV=container
    ports:
      - 8082:8082

  auth-api:
    build: './auth-api'
    container_name: auth-api
    depends_on:
      - auth-db
    networks:
      - sales-network
    environment:
      - JWT_SECRET=f4c77928acb18a37a7f8b5e7af63f4fd
      - DB_HOST=auth-db
      - DB_PORT=5432
      - DB_NAME=auth-db
      - DB_USER=admin
      - DB_PASS=123456
      - PORT=8080
      - NODE_ENV=container
    ports:
      - 8080:8080

networks:
  sales-network:
    driver: bridge
