server:
  port: ${PORT:8081}

spring:

  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

  application:
    name: product-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product-db
    username: admin
    password: 123456
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql
    maxActive: 3

  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USER:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

app-config:

  services:
    sales: http://${SALES_HOST:localhost}:${SALES_PORT:8082}

  secrets:
    jwt-secret: ${JWT_SECRET:4df5622ce61305cc2da15c8d9ddbbe94}

  rabbit:
    exchange:
      product: product.topic

    routingKey:
      product-stock: product-stock-update.routingKey
      sales-confirmation: sales-confirmation.routingKey

    queue:
      product-stock: product-stock.queue
      sales-confirmation: sales-confirmation.queue